Repository pagopa/pagopa-spontaneous-payments, pull requests merged in 2022-08, with the labels that each got.

#20 [Ppd 271] fix crud enrollments
  openapi/openapi.json
  src/main/java/it/gov/pagopa/spontaneouspayment/model/EnrollmentModel.java
  src/main/java/it/gov/pagopa/spontaneouspayment/model/response/EnrollmentModelResponse.java
  src/main/java/it/gov/pagopa/spontaneouspayment/service/EnrollmentsService.java
  src/test/java/it/gov/pagopa/spontaneouspayment/config/TestUtil.java
  src/test/java/it/gov/pagopa/spontaneouspayment/controller/EnrollmentsControllerTest.java
  src/test/java/it/gov/pagopa/spontaneouspayment/service/EnrollmentsServiceTest.java
Labels: bug

#23 fix: github action and swagger
  .github/workflows/update_infra.yml
  openapi/generate_openapi.sh
  openapi/openapi.json
Labels: ignore-for-release

#25 Ppd 251 gps integration test
  integration-test/README.md
  integration-test/config/properties.json
  integration-test/features/organizations.feature
  integration-test/features/payments.feature
  integration-test/package.json
  integration-test/step_definitions/support/common.js
  integration-test/step_definitions/support/gps_client.js
  integration-test/step_definitions/support/organizations_steps.js
  integration-test/step_definitions/support/payments_steps.js
  integration-test/step_definitions/support/steps.js
  load-test/init-db/init_gps_db_services.js
  openapi/openapi.json
  src/main/java/it/gov/pagopa/spontaneouspayment/controller/impl/BaseController.java
  src/main/java/it/gov/pagopa/spontaneouspayment/service/PaymentsService.java
  src/main/resources/application-dev.properties
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/spontaneouspayment/controller/BaseControllerTest.java
Labels: ignore-for-release

#26 [PPD 275] create and update service
  openapi/openapi.json
  src/main/java/it/gov/pagopa/spontaneouspayment/controller/IEnrollmentsController.java
  src/main/java/it/gov/pagopa/spontaneouspayment/controller/IServicesController.java
  src/main/java/it/gov/pagopa/spontaneouspayment/controller/impl/ServicesController.java
  src/main/java/it/gov/pagopa/spontaneouspayment/entity/Service.java
  src/main/java/it/gov/pagopa/spontaneouspayment/model/ServiceConfigPropertyModel.java
  src/main/java/it/gov/pagopa/spontaneouspayment/model/ServiceDetailModel.java
  src/main/java/it/gov/pagopa/spontaneouspayment/model/ServiceDetailUpdModel.java
  src/main/java/it/gov/pagopa/spontaneouspayment/model/ServicePropertyModel.java
  src/main/java/it/gov/pagopa/spontaneouspayment/model/response/ServiceDetailModelResponse.java
  src/main/java/it/gov/pagopa/spontaneouspayment/model/response/ServicePropertyModelResponse.java
  src/main/java/it/gov/pagopa/spontaneouspayment/service/ServicesService.java
  src/test/java/it/gov/pagopa/spontaneouspayment/config/TestUtil.java
  src/test/java/it/gov/pagopa/spontaneouspayment/controller/ServicesControllerTest.java
  src/test/java/it/gov/pagopa/spontaneouspayment/service/ServicesServiceTest.java
Labels: enhancement
